services:
  #jenkins:
  #  build:
  #    context: ./jenkins
  #  ports:
  #    - "5000:8080"
  #node:
  #  build:
  #    context: ./node
  #go:
  #  build:
  #    context: ./go
  nginx:
    restart: always
    image: nginx:1-alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./../static:/usr/share/nginx/html